### ISSUE TITLE
SQL Injections generate zero payloads

### ISSUE THREAD

**Issue by SHMAUS-Carter** [h0nus/QRGen#2]
$ python qrgen.py -l 0

  e88 88e   888 88e    e88'Y88
 d888 888b  888 888D  d888  'Y   ,e e,  888 8e
C8888 8888D 888 88"  C8888 eeee d88 88b 888 88b
 Y888 888P  888 b,    Y888 888P 888   , 888 888
  "88 88"   888 88b,   "88 88"   "YeeP" 888 888
      b
      8b,    QRGen ~ v0.1 ~ by h0nus

Payload path exist, continuing...
Path already cleared or deleted..
Generated 0 payloads!
Thanks for using QRGen, made by H0nus..

Commented out the auto open last generated section to prevent an error when it tried to display a none existent output

**Comment by h0nus** [comment]
You should have a directory named "words" with a file called sqli without extensions.
This directory should be in the same position of qrgen.py.
Can you give me more details?

**Comment by SHMAUS-Carter** [comment]
![Screenshot_20190902-191443_FX](https://user-images.githubusercontent.com/531233/64136242-00a3fd80-cdb6-11e9-99fd-28c2bcb8e58b.jpg)
I make use of termux and that's the only mode that has issues

**Comment by SHMAUS-Carter** [comment]
Hit closed by mistake

**Comment by SHMAUS-Carter** [comment]
python qrgen.py -l 0

  e88 88e   888 88e    e88'Y88
 d888 888b  888 888D  d888  'Y   ,e e,  888 8e
C8888 8888D 888 88"  C8888 eeee d88 88b 888 88b
 Y888 888P  888 b,    Y888 888P 888   , 888 888
  "88 88"   888 88b,   "88 88"   "YeeP" 888 888
      b
      8b,    QRGen ~ v0.1 ~ by h0nus

Payload path exist, continuing...
Path already cleared or deleted..
Generated 0 payloads!
Traceback (most recent call last):
  File "qrgen.py", line 70, in <module>
    Image.open("genqr/payload-{}.png".format(i-1)).show()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'genqr/payload--1.png'

**Comment by h0nus** [comment]
By what i see it's really strange.
Can you try to use the -w command and give him words/sqli ? 
like this:
`python3 qrgen.py -w words/sqli`
if this doesn't work try:
`python3 qrgen.py -w $(pwd)/words/sqli`
and let me know.

**Comment by SHMAUS-Carter** [comment]
$ cd storage/shared/QRGen/
$ python3 qrgen.py -w words/sqli

  e88 88e   888 88e    e88'Y88
 d888 888b  888 888D  d888  'Y   ,e e,  888 8e
C8888 8888D 888 88"  C8888 eeee d88 88b 888 88b
 Y888 888P  888 b,    Y888 888P 888   , 888 888
  "88 88"   888 88b,   "88 88"   "YeeP" 888 888
      b
      8b,    QRGen ~ v0.1 ~ by h0nus

Payload path exist, continuing...
Path already cleared or deleted..
Generated 158 payloads!
Opening last generated payload...
Thanks for using QRGen, made by H0nus..
$

**Comment by SHMAUS-Carter** [comment]
Seems like an issue with it interpreting the 0 for the selection.

**Comment by h0nus** [comment]
yeah, it seems a problem with that.
What if you use number 1? what payload are outputted?

**Comment by SHMAUS-Carter** [comment]
python qrgen.py -l 1

  e88 88e   888 88e    e88'Y88
 d888 888b  888 888D  d888  'Y   ,e e,  888 8e
C8888 8888D 888 88"  C8888 eeee d88 88b 888 88b
 Y888 888P  888 b,    Y888 888P 888   , 888 888
  "88 88"   888 88b,   "88 88"   "YeeP" 888 888
      b
      8b,    QRGen ~ v0.1 ~ by h0nus

Payload path exist, continuing...
Path already cleared or deleted..
Generated 113 payloads!
Opening last generated payload...
Thanks for using QRGen, made by H0nus..

**Comment by h0nus** [comment]
That's strange.
At the moment, please, use the -w variant.
Actually i'm busy on another tool.
I'll keep this issue open to remind me to fix, be patient.
Cheers

**Comment by SHMAUS-Carter** [comment]
[out.txt](https://github.com/h0nus/QRGen/files/3567384/out.txt)
Will do in case you need it heres the output of all options with the line
Image.open("genqr/payload-{}.png".format(i-1)).show()
Commented out

**Comment by Samoxiaki** [comment]
I solved the problem changing this:

![Orig](https://user-images.githubusercontent.com/43545667/65134259-442c7780-da04-11e9-85f1-803279a5f521.png)

to this:

![Mod](https://user-images.githubusercontent.com/43545667/65134347-70e08f00-da04-11e9-9527-9845b7621768.png)

**Comment by h0nus** [comment]
If you fixed it, please do a pull request and i'll accept it :smile:
