### ISSUE TITLE
can't create payload- path not found

### ISSUE THREAD

**Issue by roybs2** [h0nus/QRGen#3]
hey I found a bug in the code, 
I tried to fixed it but I don't have permissions
I added this:
    if not os.path.exists("genqr"):
        os.mkdir("genqr")
in line 68.
thanks.

**Comment by h0nus** [comment]
you can try to do a pull request.
By the way now i'm really busy on another tool and work. I'll add asap.
Thanks :)

**Comment by Samoxiaki** [comment]
I also fixed this in my last Pull request. It needed indentation and importing "os".

**Comment by h0nus** [comment]
thanks for your help :)
