### ISSUE TITLE
Adding Urls to This

### ISSUE THREAD

**Issue by 1NEGROUP** [h0nus/QRGen#7]
I am Just curious if This is a Feature
Or if this could be an added feature

**Comment by h0nus** [comment]
Can you give more informations about this feature?
Or an example? Thanks

**Comment by dCr01** [comment]
> Hey sorry about the very delayed response. So i basically was wanting to know if this program has the ability to generate QRCodes with URL's, like this - https://qr-creator.com/  

Just use a word list that's made up of the URLs that you want to generate QRs for.
